/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package travel.agency.GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import travel.agency.Data.FlightData;
import travel.agency.Date1;
import travel.agency.Flight;
/**
 *
 * @author sony
 */
public class AddFlight extends java.awt.Dialog {

    /**
     * Creates new form AddFlight
     */
    public AddFlight(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){ private Image image;
            {
                try {
                    image = ImageIO.read(new File("C:\\Users\\sony\\Desktop\\new.jpg"));
                } catch (IOException
                    e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }};
            jLabel1 = new javax.swing.JLabel();
            code = new javax.swing.JTextField();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel10 = new javax.swing.JLabel();
            insert = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            flightTable = new javax.swing.JTable();
            exit = new javax.swing.JButton();
            jLabel9 = new javax.swing.JLabel();
            capacity = new javax.swing.JTextField();
            source = new javax.swing.JComboBox();
            destination = new javax.swing.JComboBox();
            company = new javax.swing.JComboBox();
            year = new javax.swing.JComboBox();
            day = new javax.swing.JComboBox();
            month = new javax.swing.JComboBox();
            hour = new javax.swing.JComboBox();
            minute = new javax.swing.JComboBox();

            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Code:");
            jDesktopPane1.add(jLabel1);
            jLabel1.setBounds(120, 90, 150, 40);

            code.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            jDesktopPane1.add(code);
            code.setBounds(270, 90, 150, 30);

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("Company:");
            jDesktopPane1.add(jLabel2);
            jLabel2.setBounds(130, 150, 100, 30);

            jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("Source:");
            jDesktopPane1.add(jLabel3);
            jLabel3.setBounds(140, 220, 90, 30);

            jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("Destination:");
            jDesktopPane1.add(jLabel4);
            jLabel4.setBounds(140, 280, 90, 20);

            jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel5.setText("Date:");
            jDesktopPane1.add(jLabel5);
            jLabel5.setBounds(150, 340, 80, 20);

            jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(255, 255, 255));
            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel6.setText("Time:");
            jDesktopPane1.add(jLabel6);
            jLabel6.setBounds(150, 390, 80, 20);

            jLabel7.setForeground(new java.awt.Color(255, 255, 255));
            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel7.setText("/");
            jDesktopPane1.add(jLabel7);
            jLabel7.setBounds(340, 350, 20, 20);

            jLabel8.setForeground(new java.awt.Color(255, 255, 255));
            jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel8.setText("/");
            jDesktopPane1.add(jLabel8);
            jLabel8.setBounds(410, 350, 20, 20);

            jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(255, 255, 255));
            jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel10.setText(":");
            jDesktopPane1.add(jLabel10);
            jLabel10.setBounds(320, 390, 20, 30);

            insert.setBackground(new java.awt.Color(51, 204, 0));
            insert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            insert.setForeground(new java.awt.Color(255, 255, 255));
            insert.setText("Insert");
            insert.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    insertActionPerformed(evt);
                }
            });
            jDesktopPane1.add(insert);
            insert.setBounds(270, 520, 80, 40);

            flightTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Code", "Company", "Source", "Destination", "Date", "Time", "capacity"
                }
            ));
            flightTable.setEnabled(false);
            jScrollPane1.setViewportView(flightTable);

            jDesktopPane1.add(jScrollPane1);
            jScrollPane1.setBounds(540, 0, 810, 340);

            exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/exit-icon.gif"))); // NOI18N
            exit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitActionPerformed(evt);
                }
            });
            jDesktopPane1.add(exit);
            exit.setBounds(1160, 530, 100, 90);

            jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(255, 255, 255));
            jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel9.setText("capacity:");
            jDesktopPane1.add(jLabel9);
            jLabel9.setBounds(160, 450, 70, 30);
            jDesktopPane1.add(capacity);
            capacity.setBounds(270, 450, 50, 30);

            source.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "تهران", "مشهد", "اصفهان", "شیراز ", " زاهدان", "اهواز", "آبادان", "یاسوج", "بیرجند", "ساری", "رشت", "گرگان", "ارومیه", "سنندج", "کرمانشاه", "کیش", "قشم", "بندرعباس", "بوشهر", "اردبیل", "لار", "رامسر", "قم", "تبریز" }));
            jDesktopPane1.add(source);
            source.setBounds(270, 220, 150, 30);

            destination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "تهران", "مشهد", "اصفهان", "شیراز ", " زاهدان", "اهواز", "آبادان", "یاسوج", "بیرجند", "ساری", "رشت", "گرگان", "ارومیه", "سنندج", "کرمانشاه", "کیش", "قشم", "بندرعباس", "بوشهر", "اردبیل", "لار", "رامسر", "قم", "تبریز" }));
            jDesktopPane1.add(destination);
            destination.setBounds(270, 280, 150, 30);

            company.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ایران ایر", "آسمان", "کیش ایر", "ماهان", "معراج", "آتا", "نفت", "کاسپین", "زاگرس" }));
            jDesktopPane1.add(company);
            company.setBounds(270, 150, 150, 30);

            year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1393", "1394", "1395", "1396", "1397", "1398", "1399", "1400" }));
            jDesktopPane1.add(year);
            year.setBounds(270, 340, 70, 30);

            day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
            jDesktopPane1.add(day);
            day.setBounds(430, 340, 50, 30);

            month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
            jDesktopPane1.add(month);
            month.setBounds(360, 340, 50, 30);

            hour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
            jDesktopPane1.add(hour);
            hour.setBounds(270, 390, 50, 30);

            minute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
            jDesktopPane1.add(minute);
            minute.setBounds(340, 390, 50, 30);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        System.exit(1);
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        refreshtable(FlightData.GetIntance().GetFlightList());
        this.code.setText("");
        this.capacity.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        if(areinputstrue()){
        Date1 date=new Date1((String)this.year.getSelectedItem(),(String)this.month.getSelectedItem(),(String)this.day.getSelectedItem(),(String)this.hour.getSelectedItem(),(String)this.minute.getSelectedItem());
        Flight flight=new Flight(this.code.getText(), (String)this.company.getSelectedItem(),(String) this.source.getSelectedItem(),(String)this.destination.getSelectedItem(), date,this.capacity.getText());
        FlightData.GetIntance().addFlight(flight);
            refreshtable(FlightData.GetIntance().GetFlightList());
        }
    }//GEN-LAST:event_insertActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       this.setVisible(false);
       new AdminMenu(null, true).setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddFlight dialog = new AddFlight(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
     public void refreshtable(ArrayList<Flight> flightlist) {
        DefaultTableModel model1 = (DefaultTableModel) this.flightTable.getModel();
        while (model1.getRowCount() != 0) {
            model1.removeRow(0);
        }
        for (Flight flight : flightlist) {
            if (flight == null) {
                continue;
            }
            
            model1.addRow(new Object[]{flight.getCode(),flight.getCompany(),flight.getSource(),flight.getDestination(),flight.getDate().toString(),flight.getDate().getClock(),flight.capacity});
        }
    }

     public boolean areinputstrue() {
        boolean aretrue = true;
        if (!this.code.getText().matches("\\d{4}+")) {
            JOptionPane.showMessageDialog(this, "شماره پرواز باید دارای چهار رقم باشد ");
            aretrue = false;
        }
         if (!this.capacity.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "قسمت ظرفیت باید بوسیله ی ارقام پر شود");
            aretrue = false;
        }
     
        return aretrue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacity;
    private javax.swing.JTextField code;
    private javax.swing.JComboBox company;
    private javax.swing.JComboBox day;
    private javax.swing.JComboBox destination;
    private javax.swing.JButton exit;
    private javax.swing.JTable flightTable;
    private javax.swing.JComboBox hour;
    private javax.swing.JButton insert;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox minute;
    private javax.swing.JComboBox month;
    private javax.swing.JComboBox source;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
