/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package travel.agency.GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import travel.agency.Data.StaffData;
import travel.agency.Staff;

/**
 *
 * @author sony
 */
public class AddStaff extends java.awt.Dialog {

    /**
     * Creates new form AddEmployee
     */
    public AddStaff(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){    private Image image;
            {
                try {
                    image = ImageIO.read(new File("C:\\Users\\sony\\Desktop\\new9.jpg"));
                } catch (IOException
                    e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }};
            jLabel1 = new javax.swing.JLabel();
            exit = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            firstName = new javax.swing.JTextField();
            lastName = new javax.swing.JTextField();
            userName = new javax.swing.JTextField();
            password = new javax.swing.JPasswordField();
            add = new javax.swing.JButton();
            jLabel6 = new javax.swing.JLabel();
            nationalcode = new javax.swing.JTextField();

            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/arman.png"))); // NOI18N
            jLabel1.setText("jLabel1");
            jDesktopPane1.add(jLabel1);
            jLabel1.setBounds(480, 10, 410, 60);

            exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/exit-icon.gif"))); // NOI18N
            exit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitActionPerformed(evt);
                }
            });
            jDesktopPane1.add(exit);
            exit.setBounds(1200, 570, 90, 100);

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("Firstname:");
            jDesktopPane1.add(jLabel2);
            jLabel2.setBounds(850, 190, 100, 40);

            jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("Lastname:");
            jDesktopPane1.add(jLabel3);
            jLabel3.setBounds(860, 260, 90, 40);

            jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel4.setText("Username:");
            jDesktopPane1.add(jLabel4);
            jLabel4.setBounds(860, 330, 90, 40);

            jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel5.setText("Password:");
            jDesktopPane1.add(jLabel5);
            jLabel5.setBounds(860, 400, 90, 40);
            jDesktopPane1.add(firstName);
            firstName.setBounds(1000, 200, 140, 30);
            jDesktopPane1.add(lastName);
            lastName.setBounds(1000, 270, 140, 30);
            jDesktopPane1.add(userName);
            userName.setBounds(1000, 340, 140, 30);
            jDesktopPane1.add(password);
            password.setBounds(1000, 410, 140, 30);

            add.setBackground(new java.awt.Color(51, 255, 51));
            add.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            add.setText("Add");
            add.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addActionPerformed(evt);
                }
            });
            jDesktopPane1.add(add);
            add.setBounds(1020, 490, 100, 50);

            jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(255, 255, 255));
            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel6.setText("Nationalcode:");
            jDesktopPane1.add(jLabel6);
            jLabel6.setBounds(840, 120, 110, 40);
            jDesktopPane1.add(nationalcode);
            nationalcode.setBounds(1000, 130, 140, 30);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
        new AdminMenu(null, true).setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if(areinputstrue()){
        Staff staff=new Staff(this.nationalcode.getText(),this.firstName.getText(),this.lastName.getText(),this.userName.getText(),this.password.getText());
        StaffData.getInstance().addStaff(staff);
        }
        
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddStaff dialog = new AddStaff(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
     public boolean areinputstrue() {
        boolean aretrue = true;

        if (!this.nationalcode.getText().matches("\\d{10}+")) {
            JOptionPane.showMessageDialog(this, "کد ملی باید دارای ده رقم باشد ");
            aretrue = false;
        }
        if (!this.firstName.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "قسمت نام را به وسیله حروف پر کنید ");
            aretrue = false;
        }
          if (!this.lastName.getText().matches("[a-zA-Z]+")){
            JOptionPane.showMessageDialog(this, "قسمت نام خانوادگی  را به وسیله حروف پر کنید ");
            aretrue = false;
        }
        if (!this.password.getText().matches("[\\w]{8,}")) {
            JOptionPane.showMessageDialog(this, "پسورد باید حداقل هشت رقم و بوسیله ی حروف بزرگ و کوچک و ارقام پر شود");
            aretrue = false;
        }
        if(this.userName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "قسمت یوزرنم را پر کنید");
            aretrue = false;
        }
        return aretrue;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton exit;
    private javax.swing.JTextField firstName;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField nationalcode;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
