/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package travel.agency.GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author sony
 */
public class ConnectionWithUs extends java.awt.Dialog {

    /**
     * Creates new form ConnectionWithUs
     */
    public ConnectionWithUs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){private Image image;
            {
                try {
                    image = ImageIO.read(new File("C:\\Users\\sony\\Desktop\\new6.jpg"));
                } catch (IOException
                    e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }};
            jLabel1 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            send = new javax.swing.JButton();
            get = new javax.swing.JButton();

            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
            });

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/arman.png"))); // NOI18N
            jDesktopPane1.add(jLabel1);
            jLabel1.setBounds(480, 20, 416, 51);

            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/exit-icon.gif"))); // NOI18N
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            jDesktopPane1.add(jButton1);
            jButton1.setBounds(1160, 550, 93, 94);

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(153, 0, 255));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("پست الکترونیکی:");
            jDesktopPane1.add(jLabel2);
            jLabel2.setBounds(1130, 160, 150, 50);

            jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(153, 0, 255));
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("armanchat70@yahoo.com");
            jDesktopPane1.add(jLabel3);
            jLabel3.setBounds(850, 164, 250, 40);

            jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(153, 0, 255));
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel4.setText("آدرس:");
            jDesktopPane1.add(jLabel4);
            jLabel4.setBounds(1140, 330, 140, 40);

            jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(153, 0, 255));
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel5.setText("تهران - پاسداران - خیابان زمرد سوم - پلاک 4");
            jDesktopPane1.add(jLabel5);
            jLabel5.setBounds(710, 330, 440, 40);

            jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(153, 0, 255));
            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel6.setText("تلفن:");
            jDesktopPane1.add(jLabel6);
            jLabel6.setBounds(1140, 260, 120, 40);

            jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(153, 0, 255));
            jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel7.setText("02188905821");
            jDesktopPane1.add(jLabel7);
            jLabel7.setBounds(870, 260, 230, 30);

            send.setBackground(new java.awt.Color(153, 51, 255));
            send.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            send.setForeground(new java.awt.Color(255, 255, 255));
            send.setText("ارسال پیام");
            send.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    sendActionPerformed(evt);
                }
            });
            jDesktopPane1.add(send);
            send.setBounds(720, 570, 160, 50);

            get.setBackground(new java.awt.Color(153, 51, 255));
            get.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            get.setForeground(new java.awt.Color(255, 255, 255));
            get.setText("مشاهده جواب پیام ها");
            get.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    getActionPerformed(evt);
                }
            });
            jDesktopPane1.add(get);
            get.setBounds(453, 570, 160, 50);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1351, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        System.exit(1);
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new CustomerMenu(null, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        this.setVisible(false);
        new SendMessage(null, true).setVisible(true);
    }//GEN-LAST:event_sendActionPerformed

    private void getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getActionPerformed
        this.setVisible(false);
        new ShowReplyMessages(null, true).setVisible(true);
    }//GEN-LAST:event_getActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConnectionWithUs dialog = new ConnectionWithUs(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton get;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables
}
