/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package travel.agency.GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import travel.agency.Data.MessageData;
import travel.agency.Data.RequestData;
import travel.agency.Data.StaffData;
import travel.agency.Flight;
import travel.agency.Message;
import travel.agency.Reply;
import travel.agency.Request;
import travel.agency.RoozaneRequest;
import travel.agency.SaatiRequest;
import travel.agency.Staff;

/**
 *
 * @author sony
 */
public class ReplyRequest extends java.awt.Dialog {
  public static Request request;
    /**
     * Creates new form ReplyRequest
     */
    public ReplyRequest(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane(){ private Image image;
            {
                try {
                    image = ImageIO.read(new File("C:\\Users\\sony\\Desktop\\b.jpg"));
                } catch (IOException
                    e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }};
            jLabel1 = new javax.swing.JLabel();
            exit = new javax.swing.JButton();
            users = new javax.swing.JComboBox();
            show = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            roozane = new javax.swing.JTable();
            rad = new javax.swing.JRadioButton();
            ghabool = new javax.swing.JRadioButton();
            reply = new javax.swing.JButton();
            jScrollPane2 = new javax.swing.JScrollPane();
            saati = new javax.swing.JTable();

            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/arman.png"))); // NOI18N
            jLabel1.setText("jLabel1");
            jDesktopPane1.add(jLabel1);
            jLabel1.setBounds(490, 20, 410, 60);

            exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/exit-icon.gif"))); // NOI18N
            exit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitActionPerformed(evt);
                }
            });
            jDesktopPane1.add(exit);
            exit.setBounds(1150, 540, 90, 100);

            jDesktopPane1.add(users);
            users.setBounds(1050, 190, 180, 30);

            show.setBackground(new java.awt.Color(51, 255, 0));
            show.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            show.setText("نمایش");
            show.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    showActionPerformed(evt);
                }
            });
            jDesktopPane1.add(show);
            show.setBounds(1090, 270, 90, 40);

            roozane.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null}
                },
                new String [] {
                    "از         ", "تا         "
                }
            ));
            jScrollPane1.setViewportView(roozane);

            jDesktopPane1.add(jScrollPane1);
            jScrollPane1.setBounds(170, 370, 210, 50);

            buttonGroup1.add(rad);
            rad.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            rad.setForeground(new java.awt.Color(255, 0, 0));
            rad.setText("رد");
            jDesktopPane1.add(rad);
            rad.setBounds(550, 380, 70, 30);

            buttonGroup1.add(ghabool);
            ghabool.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
            ghabool.setForeground(new java.awt.Color(51, 255, 0));
            ghabool.setText("قبول");
            jDesktopPane1.add(ghabool);
            ghabool.setBounds(410, 380, 80, 30);

            reply.setBackground(new java.awt.Color(51, 255, 0));
            reply.setText("ارسال پاسخ");
            reply.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    replyActionPerformed(evt);
                }
            });
            jDesktopPane1.add(reply);
            reply.setBounds(460, 450, 100, 40);

            saati.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null}
                },
                new String [] {
                    "تاریخ       ", "از         ", "تا         "
                }
            ));
            jScrollPane2.setViewportView(saati);

            jDesktopPane1.add(jScrollPane2);
            jScrollPane2.setBounds(660, 370, 452, 50);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1347, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.roozane.setVisible(false);
        this.saati.setVisible(false);
        this.roozane.setEnabled(false);
        this.saati.setEnabled(false);
        this.reply.setVisible(false);
        this.rad.setVisible(false);
        this.ghabool.setVisible(false);
        refreshComboBox();
        
    }//GEN-LAST:event_formWindowOpened

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
        new AdminMenu(null, true).setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        if(this.users.getSelectedItem()!=null){
        request=RequestData.Getinstance().searchRequest((String)this.users.getSelectedItem());
        if(request instanceof SaatiRequest){
            SaatiRequest saatiRequest=(SaatiRequest)request;
        this.saati.setVisible(true);
        this.reply.setVisible(true);
        this.rad.setVisible(true);
        this.ghabool.setVisible(true);
         DefaultTableModel model1 = (DefaultTableModel) this.saati.getModel();
        while (model1.getRowCount() != 0) {
            model1.removeRow(0);
        }
            
            model1.addRow(new Object[]{saatiRequest.getDate(),saatiRequest.getTime1(),saatiRequest.getTime2()});
        }
        
        else{
        this.roozane.setVisible(true);
        RoozaneRequest roozaneRequest=(RoozaneRequest)request;
        this.reply.setVisible(true);
        this.rad.setVisible(true);
        this.ghabool.setVisible(true);
           DefaultTableModel model1 = (DefaultTableModel) this.roozane.getModel();
        while (model1.getRowCount() != 0) {
            model1.removeRow(0);
        }
            
            model1.addRow(new Object[]{roozaneRequest.getDate1(),roozaneRequest.getDate2()});
        }
    }
        else{
            JOptionPane.showMessageDialog(null,"ابتدا کارمند را انتخاب کنید");
        }
    }//GEN-LAST:event_showActionPerformed

    private void replyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replyActionPerformed
        if(this.users.getSelectedItem()!=null){
        if(this.ghabool.isSelected()){
            request.reply=Reply.yes;
            JOptionPane.showMessageDialog(null,"پاسخ ارسال شد");
        }
        else{
             request.reply=Reply.no;
              JOptionPane.showMessageDialog(null,"پاسخ ارسال شد");
        }
        }
        else{
             JOptionPane.showMessageDialog(null,"ابتدا کارمند را انتخاب کنید");
        }
    }//GEN-LAST:event_replyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReplyRequest dialog = new ReplyRequest(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void refreshComboBox(){
          
        this.users.removeAllItems();
        ArrayList<Staff> staffList;
    staffList=StaffData.getInstance().staffHasRequest();
          for (Staff staff:staffList) {
            this.users.addItem(staff.getUserName());
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton ghabool;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rad;
    private javax.swing.JButton reply;
    private javax.swing.JTable roozane;
    private javax.swing.JTable saati;
    private javax.swing.JButton show;
    private javax.swing.JComboBox users;
    // End of variables declaration//GEN-END:variables
}
