/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package travel.agency.GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import travel.agency.Data.MessageData;
import travel.agency.Message;

/**
 *
 * @author sony
 */
public class SendMessage extends java.awt.Dialog {

    /**
     * Creates new form WriteMessege
     */
    public SendMessage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){ private Image image;
            {
                try {
                    image = ImageIO.read(new File("C:\\Users\\sony\\Desktop\\new8.jpg"));
                } catch (IOException
                    e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }};
            send = new javax.swing.JButton();
            subject = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            text = new javax.swing.JTextArea();
            jLabel2 = new javax.swing.JLabel();
            exit = new javax.swing.JButton();
            jLabel3 = new javax.swing.JLabel();

            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
            });

            send.setBackground(new java.awt.Color(51, 255, 51));
            send.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            send.setText("send");
            send.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    sendActionPerformed(evt);
                }
            });
            jDesktopPane1.add(send);
            send.setBounds(360, 520, 101, 41);

            subject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jDesktopPane1.add(subject);
            subject.setBounds(220, 180, 230, 34);

            jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("subject:");
            jDesktopPane1.add(jLabel1);
            jLabel1.setBounds(70, 180, 120, 30);

            text.setColumns(20);
            text.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
            text.setRows(5);
            jScrollPane1.setViewportView(text);

            jDesktopPane1.add(jScrollPane1);
            jScrollPane1.setBounds(220, 240, 390, 220);

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("messege:");
            jDesktopPane1.add(jLabel2);
            jLabel2.setBounds(70, 290, 100, 40);

            exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/exit-icon.gif"))); // NOI18N
            exit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitActionPerformed(evt);
                }
            });
            jDesktopPane1.add(exit);
            exit.setBounds(1160, 550, 90, 90);

            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/arman.png"))); // NOI18N
            jDesktopPane1.add(jLabel3);
            jLabel3.setBounds(500, 20, 416, 60);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        System.exit(1);
    }//GEN-LAST:event_closeDialog

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
        new ConnectionWithUs(null, true).setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        int height=HEIGHT-1;
        int height2=HEIGHT-1;
        if(this.subject.getText().equals(""))
        height=JOptionPane.showConfirmDialog(null,"پیام موضوع ندارد به هر حال ارسال شود ؟", null,HEIGHT);
        if(this.text.getText().equals("")&&height!=HEIGHT)
        height2=JOptionPane.showConfirmDialog(null,"پیام خالی هست به هر حال ارسال شود ؟", null,HEIGHT);
        if(this.subject.getText().equals("")||this.text.getText().equals("")){
            if(height!=HEIGHT&&height2!=HEIGHT){
                Message messege=new Message(CustomerLogIn.found,this.subject.getText(),this.text.getText());
                MessageData.getInstance().addMessege(messege);
                JOptionPane.showMessageDialog(null,"پیام ارسال شد");
            }
        }
        else{
            Message messege=new Message(CustomerLogIn.found,this.subject.getText(),this.text.getText());
             MessageData.getInstance().addMessege(messege);
             JOptionPane.showMessageDialog(null,"پیام ارسال شد");
        }
    }//GEN-LAST:event_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SendMessage dialog = new SendMessage(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton send;
    private javax.swing.JTextField subject;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
