/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel.agency.GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import travel.agency.Data.RequestData;
import travel.agency.Data.StaffData;
import travel.agency.Reply;
import travel.agency.Request;
import travel.agency.RoozaneRequest;
import travel.agency.SaatiRequest;

/**
 *
 * @author sony
 */
public class SendRequest extends java.awt.Dialog {

    /**
     * Creates new form Request
     */
    public SendRequest(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane(){  private Image image;
            {
                try {
                    image = ImageIO.read(new File("C:\\Users\\sony\\Desktop\\new7.jpg"));
                } catch (IOException
                    e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }};
            saati = new javax.swing.JRadioButton();
            roozane = new javax.swing.JRadioButton();
            s1 = new javax.swing.JLabel();
            s4 = new javax.swing.JLabel();
            year1 = new javax.swing.JComboBox();
            s3 = new javax.swing.JLabel();
            month1 = new javax.swing.JComboBox();
            s2 = new javax.swing.JLabel();
            day1 = new javax.swing.JComboBox();
            day2 = new javax.swing.JComboBox();
            s5 = new javax.swing.JLabel();
            month2 = new javax.swing.JComboBox();
            s6 = new javax.swing.JLabel();
            year2 = new javax.swing.JComboBox();
            send = new javax.swing.JButton();
            r = new javax.swing.JLabel();
            day3 = new javax.swing.JComboBox();
            r2 = new javax.swing.JLabel();
            month3 = new javax.swing.JComboBox();
            r3 = new javax.swing.JLabel();
            year3 = new javax.swing.JComboBox();
            r4 = new javax.swing.JLabel();
            hour1 = new javax.swing.JComboBox();
            r5 = new javax.swing.JLabel();
            minute1 = new javax.swing.JComboBox();
            r6 = new javax.swing.JLabel();
            minute2 = new javax.swing.JComboBox();
            hour2 = new javax.swing.JComboBox();
            r7 = new javax.swing.JLabel();
            exit = new javax.swing.JButton();
            Show = new javax.swing.JButton();

            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            buttonGroup1.add(saati);
            saati.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            saati.setText("مرخصی ساعتی");
            saati.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    saatiItemStateChanged(evt);
                }
            });
            jDesktopPane1.add(saati);
            saati.setBounds(930, 80, 130, 30);

            buttonGroup1.add(roozane);
            roozane.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            roozane.setText("مرخصی روزانه");
            jDesktopPane1.add(roozane);
            roozane.setBounds(1130, 80, 120, 30);

            s1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            s1.setForeground(new java.awt.Color(255, 51, 51));
            s1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            s1.setText("از");
            jDesktopPane1.add(s1);
            s1.setBounds(1190, 200, 50, 30);

            s4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            s4.setForeground(new java.awt.Color(255, 51, 51));
            s4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            s4.setText("تا");
            jDesktopPane1.add(s4);
            s4.setBounds(1200, 290, 40, 30);

            year1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            year1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1393", "1394", "1395" }));
            jDesktopPane1.add(year1);
            year1.setBounds(950, 200, 70, 30);

            s3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            s3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            s3.setText("/");
            jDesktopPane1.add(s3);
            s3.setBounds(1020, 200, 30, 30);

            month1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            month1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
            jDesktopPane1.add(month1);
            month1.setBounds(1060, 200, 40, 30);

            s2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            s2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            s2.setText("/");
            jDesktopPane1.add(s2);
            s2.setBounds(1100, 200, 30, 30);

            day1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
            jDesktopPane1.add(day1);
            day1.setBounds(1140, 200, 40, 30);

            day2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
            jDesktopPane1.add(day2);
            day2.setBounds(1140, 290, 40, 30);

            s5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            s5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            s5.setText("/");
            jDesktopPane1.add(s5);
            s5.setBounds(1110, 290, 30, 30);

            month2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
            jDesktopPane1.add(month2);
            month2.setBounds(1060, 290, 40, 30);

            s6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            s6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            s6.setText("/");
            jDesktopPane1.add(s6);
            s6.setBounds(1020, 290, 30, 30);

            year2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            year2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1393", "1394", "1395" }));
            jDesktopPane1.add(year2);
            year2.setBounds(960, 290, 54, 30);

            send.setBackground(new java.awt.Color(51, 255, 0));
            send.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            send.setText("ثبت ");
            send.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    sendActionPerformed(evt);
                }
            });
            jDesktopPane1.add(send);
            send.setBounds(1040, 380, 90, 50);

            r.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            r.setForeground(new java.awt.Color(255, 51, 51));
            r.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            r.setText("تاریخ:");
            jDesktopPane1.add(r);
            r.setBounds(1200, 150, 50, 40);

            day3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
            jDesktopPane1.add(day3);
            day3.setBounds(1140, 150, 40, 30);

            r2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            r2.setText("/");
            jDesktopPane1.add(r2);
            r2.setBounds(1110, 150, 30, 30);

            month3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
            jDesktopPane1.add(month3);
            month3.setBounds(1060, 150, 40, 30);

            r3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            r3.setText("/");
            jDesktopPane1.add(r3);
            r3.setBounds(1020, 150, 30, 30);

            year3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1393", "1394", "1395" }));
            jDesktopPane1.add(year3);
            year3.setBounds(950, 150, 70, 30);

            r4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            r4.setForeground(new java.awt.Color(255, 51, 51));
            r4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            r4.setText("از");
            jDesktopPane1.add(r4);
            r4.setBounds(1200, 250, 34, 30);

            hour1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
            jDesktopPane1.add(hour1);
            hour1.setBounds(1040, 250, 40, 30);

            r5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            r5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            r5.setText(":");
            jDesktopPane1.add(r5);
            r5.setBounds(1080, 250, 30, 30);

            minute1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
            jDesktopPane1.add(minute1);
            minute1.setBounds(1110, 250, 40, 30);

            r6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            r6.setForeground(new java.awt.Color(255, 51, 51));
            r6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            r6.setText("تا");
            jDesktopPane1.add(r6);
            r6.setBounds(1210, 330, 30, 30);

            minute2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
            jDesktopPane1.add(minute2);
            minute2.setBounds(1110, 330, 40, 30);

            hour2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
            jDesktopPane1.add(hour2);
            hour2.setBounds(1040, 330, 40, 30);

            r7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            r7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            r7.setText(":");
            jDesktopPane1.add(r7);
            r7.setBounds(1080, 330, 30, 30);

            exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/exit-icon.gif"))); // NOI18N
            exit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitActionPerformed(evt);
                }
            });
            jDesktopPane1.add(exit);
            exit.setBounds(1170, 550, 90, 100);

            Show.setBackground(new java.awt.Color(51, 255, 51));
            Show.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            Show.setText("مشاهده پاسخ درخواست");
            Show.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ShowActionPerformed(evt);
                }
            });
            jDesktopPane1.add(Show);
            Show.setBounds(600, 590, 170, 60);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.roozane.setSelected(true);
        this.r.setVisible(false);
        this.r2.setVisible(false);
        this.r3.setVisible(false);
        this.r4.setVisible(false);
        this.r5.setVisible(false);
        this.r6.setVisible(false);
        this.r7.setVisible(false);
        this.year3.setVisible(false);
        this.month3.setVisible(false);
        this.day3.setVisible(false);
        this.hour1.setVisible(false);
        this.minute1.setVisible(false);
        this.hour2.setVisible(false);
        this.minute2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void saatiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_saatiItemStateChanged
        if (this.saati.isSelected()) {
            this.s1.setVisible(false);
            this.s2.setVisible(false);
            this.s3.setVisible(false);
            this.s4.setVisible(false);
            this.s5.setVisible(false);
            this.s6.setVisible(false);
            this.day1.setVisible(false);
            this.day2.setVisible(false);
            this.month1.setVisible(false);
            this.month2.setVisible(false);
            this.year1.setVisible(false);
            this.year2.setVisible(false);
            this.r.setVisible(true);
            this.r2.setVisible(true);
            this.r3.setVisible(true);
            this.r4.setVisible(true);
            this.r5.setVisible(true);
            this.r6.setVisible(true);
            this.r7.setVisible(true);
            this.year3.setVisible(true);
            this.month3.setVisible(true);
            this.day3.setVisible(true);
            this.hour1.setVisible(true);
            this.minute1.setVisible(true);
            this.hour2.setVisible(true);
            this.minute2.setVisible(true);
        } else {
            this.s1.setVisible(true);
            this.s2.setVisible(true);
            this.s3.setVisible(true);
            this.s4.setVisible(true);
            this.s5.setVisible(true);
            this.s6.setVisible(true);
            this.day1.setVisible(true);
            this.day2.setVisible(true);
            this.month1.setVisible(true);
            this.month2.setVisible(true);
            this.year1.setVisible(true);
            this.year2.setVisible(true);
            this.r.setVisible(false);
            this.r2.setVisible(false);
            this.r3.setVisible(false);
            this.r4.setVisible(false);
            this.r5.setVisible(false);
            this.r6.setVisible(false);
            this.r7.setVisible(false);
            this.year3.setVisible(false);
            this.month3.setVisible(false);
            this.day3.setVisible(false);
            this.hour1.setVisible(false);
            this.minute1.setVisible(false);
            this.hour2.setVisible(false);
            this.minute2.setVisible(false);
        }
    }//GEN-LAST:event_saatiItemStateChanged

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
       if(!StaffLogIn.found.hasRequest){
        if(this.roozane.isSelected()){
            String date1=(String)this.year1.getSelectedItem()+"/"+(String)this.month1.getSelectedItem()+"/"+(String)this.day1.getSelectedItem();
            String date2=(String)this.year2.getSelectedItem()+"/"+(String)this.month2.getSelectedItem()+"/"+(String)this.day2.getSelectedItem();
            RoozaneRequest roozaneRequest=new RoozaneRequest(StaffLogIn.found,date1,date2);
            RequestData.Getinstance().addRequest(roozaneRequest);
            StaffLogIn.found.hasRequest=true;
        }
        else{
             String date=(String)this.year3.getSelectedItem()+"/"+(String)this.month3.getSelectedItem()+"/"+(String)this.day3.getSelectedItem();
             String time1=(String)this.hour1.getSelectedItem()+":"+(String)this.minute1.getSelectedItem();
             String time2=(String)this.hour2.getSelectedItem()+":"+(String)this.minute2.getSelectedItem();
             SaatiRequest saatiRequest=new SaatiRequest(StaffLogIn.found,date,time1,time2);
             RequestData.Getinstance().addRequest(saatiRequest);
             StaffLogIn.found.hasRequest=true;
        }
       }
       else{
           JOptionPane.showMessageDialog(null,"شما قبلا درخواست ارسال کرده اید");
       }
    }//GEN-LAST:event_sendActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
        new StaffMenu(null, true).setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
         boolean hasRequest2=false;
        for(Request request:RequestData.Getinstance().getRequestList()){
            if(request.sender.getNationalCode().equals(StaffLogIn.found.getNationalCode())){
                hasRequest2=true;
                if(request.reply==Reply.yes){
                    JOptionPane.showMessageDialog(null, "درخواست شما پذیرفته شده است");
                    StaffLogIn.found.hasRequest=false;
                  
                }
                if(request.reply==Reply.no){
                    JOptionPane.showMessageDialog(null, "درخواست شما پذیرفته نشده است");
                    StaffLogIn.found.hasRequest=false;
                    
                }
                if(request.reply==Reply.any)
                    JOptionPane.showMessageDialog(null, "درخواست شما هنوز بررسی نشده است");
            }
        }
            if(hasRequest2==false){
                JOptionPane.showMessageDialog(null, "شما درخواستی ارسال نکرده اید");
            }
        
    }//GEN-LAST:event_ShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SendRequest dialog = new SendRequest(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Show;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox day1;
    private javax.swing.JComboBox day2;
    private javax.swing.JComboBox day3;
    private javax.swing.JButton exit;
    private javax.swing.JComboBox hour1;
    private javax.swing.JComboBox hour2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JComboBox minute1;
    private javax.swing.JComboBox minute2;
    private javax.swing.JComboBox month1;
    private javax.swing.JComboBox month2;
    private javax.swing.JComboBox month3;
    private javax.swing.JLabel r;
    private javax.swing.JLabel r2;
    private javax.swing.JLabel r3;
    private javax.swing.JLabel r4;
    private javax.swing.JLabel r5;
    private javax.swing.JLabel r6;
    private javax.swing.JLabel r7;
    private javax.swing.JRadioButton roozane;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JRadioButton saati;
    private javax.swing.JButton send;
    private javax.swing.JComboBox year1;
    private javax.swing.JComboBox year2;
    private javax.swing.JComboBox year3;
    // End of variables declaration//GEN-END:variables
}
