/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package travel.agency.GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import travel.agency.*;
import travel.agency.Data.FlightData;

/**
 *
 * @author sony
 */
public class ShowFlightList extends java.awt.Dialog {

    /**
     * Creates new form ShowFlightList
     */
    public ShowFlightList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){private Image image;
            {
                try {
                    image = ImageIO.read(new File("C:\\Users\\sony\\Desktop\\new7.jpg"));
                } catch (IOException
                    e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }};
            jScrollPane1 = new javax.swing.JScrollPane();
            flights = new javax.swing.JTable();
            exit = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            mabda = new javax.swing.JComboBox();
            maghsad = new javax.swing.JComboBox();
            search = new javax.swing.JButton();

            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            flights.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null}
                },
                new String [] {
                    "Code", "Company", "Source", "Destination", "Date", "Time", "Capacity", "Number of buy"
                }
            ));
            jScrollPane1.setViewportView(flights);

            jDesktopPane1.add(jScrollPane1);
            jScrollPane1.setBounds(110, 10, 1100, 280);

            exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/exit-icon.gif"))); // NOI18N
            exit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitActionPerformed(evt);
                }
            });
            jDesktopPane1.add(exit);
            exit.setBounds(1140, 560, 100, 90);

            jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("مبدا:");
            jDesktopPane1.add(jLabel1);
            jLabel1.setBounds(1140, 340, 60, 30);

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("مقصد:");
            jDesktopPane1.add(jLabel2);
            jLabel2.setBounds(1140, 410, 60, 30);

            mabda.setBackground(new java.awt.Color(255, 255, 153));
            mabda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            mabda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "تهران", "مشهد", "اصفهان", "شیراز ", " زاهدان", "اهواز", "آبادان", "یاسوج", "بیرجند", "ساری", "رشت", "گرگان", "ارومیه", "سنندج", "کرمانشاه", "کیش", "قشم", "بندرعباس", "بوشهر", "اردبیل", "لار", "رامسر", "قم", "تبریز" }));
            jDesktopPane1.add(mabda);
            mabda.setBounds(980, 340, 130, 30);

            maghsad.setBackground(new java.awt.Color(255, 255, 153));
            maghsad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            maghsad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "تهران", "مشهد", "اصفهان", "شیراز ", " زاهدان", "اهواز", "آبادان", "یاسوج", "بیرجند", "ساری", "رشت", "گرگان", "ارومیه", "سنندج", "کرمانشاه", "کیش", "قشم", "بندرعباس", "بوشهر", "اردبیل", "لار", "رامسر", "قم", "تبریز" }));
            jDesktopPane1.add(maghsad);
            maghsad.setBounds(980, 410, 130, 30);

            search.setBackground(new java.awt.Color(102, 255, 51));
            search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            search.setText("جستجو");
            search.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    searchActionPerformed(evt);
                }
            });
            jDesktopPane1.add(search);
            search.setBounds(813, 370, 90, 40);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1355, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        System.exit(1);
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        refreshTable(FlightData.GetIntance().GetFlightList());
    }//GEN-LAST:event_formWindowOpened

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
        new AdminMenu(null, true).setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        refreshTable2(FlightData.GetIntance().GetFlightList());
         if(this.flights.getRowCount()==0)
            JOptionPane.showMessageDialog(null,"پروازی در این مسیر موجود نمی باشد");
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShowFlightList dialog = new ShowFlightList(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
   public void refreshTable(ArrayList<Flight> flightList) {
        DefaultTableModel model1 = (DefaultTableModel) this.flights.getModel();
        while (model1.getRowCount() != 0) {
            model1.removeRow(0);
        }
        for (Flight flight :flightList ) {
            if (flight == null) {
                continue;
            }
            
            model1.addRow(new Object[]{flight.getCode(),flight.getCompany(),flight.getSource(),flight.getDestination(),flight.getDate().toString(),flight.getDate().getClock(),flight.capacity,flight.ticketCount});
        }
    }
   public void refreshTable2(ArrayList<Flight> flightList){
        DefaultTableModel model1 = (DefaultTableModel) this.flights.getModel();
        while (model1.getRowCount() != 0) {
            model1.removeRow(0);
        }
        for (Flight flight :flightList ) {
            if (flight == null) {
                continue;
            }
             if(flight.getSource().equals((String)this.mabda.getSelectedItem())&&flight.getDestination().equals((String)this.maghsad.getSelectedItem()))
            model1.addRow(new Object[]{flight.getCode(),flight.getCompany(),flight.getSource(),flight.getDestination(),flight.getDate().toString(),flight.getDate().getClock(),flight.capacity,flight.ticketCount});
        }
        
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JTable flights;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox mabda;
    private javax.swing.JComboBox maghsad;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
