/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package travel.agency.GUI;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import travel.agency.Data.StaffData;
import travel.agency.Staff;

/**
 *
 * @author sony
 */
public class StaffLogIn extends java.awt.Dialog {
   public static Staff found;
    /**
     * Creates new form EmployeeLogIn
     */
    public StaffLogIn(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){ private Image image;
            {
                try {
                    image = ImageIO.read(new File("C:\\Users\\sony\\Desktop\\inside.jpg"));
                } catch (IOException
                    e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }};
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            password = new javax.swing.JPasswordField();
            enter = new javax.swing.JButton();
            exit = new javax.swing.JButton();
            jLabel3 = new javax.swing.JLabel();
            userName = new javax.swing.JTextField();

            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/arman.png"))); // NOI18N
            jLabel1.setText("jLabel1");
            jDesktopPane1.add(jLabel1);
            jLabel1.setBounds(450, 0, 410, 60);

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 0, 0));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("password:");
            jDesktopPane1.add(jLabel2);
            jLabel2.setBounds(500, 130, 120, 50);

            password.setBackground(new java.awt.Color(255, 255, 153));
            jDesktopPane1.add(password);
            password.setBounds(710, 140, 160, 30);

            enter.setBackground(new java.awt.Color(51, 255, 51));
            enter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            enter.setText("Enter");
            enter.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    enterActionPerformed(evt);
                }
            });
            jDesktopPane1.add(enter);
            enter.setBounds(620, 200, 100, 40);

            exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/agency/GUI/exit-icon.gif"))); // NOI18N
            exit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitActionPerformed(evt);
                }
            });
            jDesktopPane1.add(exit);
            exit.setBounds(1160, 540, 90, 90);

            jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 0, 0));
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("Username:");
            jDesktopPane1.add(jLabel3);
            jLabel3.setBounds(510, 80, 100, 40);

            userName.setBackground(new java.awt.Color(255, 255, 153));
            jDesktopPane1.add(userName);
            userName.setBounds(710, 90, 160, 30);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1351, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
        new EnterFrame().setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
       if(areinputstrue()){
        found=StaffData.getInstance().staffLogIn(this.userName.getText(),this.password.getText());
       if(found!=null){
           this.setVisible(false);
           new StaffMenu(null, true).setVisible(true);
       }
       else{
            JOptionPane.showMessageDialog(this,"نام کاربری یا گذرواژه اشتباه است");
       }
       }
    }//GEN-LAST:event_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StaffLogIn dialog = new StaffLogIn(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
   public boolean areinputstrue() {
        boolean aretrue = true;
        if (this.password.getText().matches("")) {
            JOptionPane.showMessageDialog(this, "تمامی قسمت ها را پر کنید");
            aretrue = false;
        }
        if(this.userName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "تمامی قسمت ها را پر کنید");
            aretrue = false;
        }
        return aretrue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter;
    private javax.swing.JButton exit;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
